name: api_practice
recipe: drupal9
config:
  php: '8.0'
  webroot: .
  xdebug: true
  config:
    php: .lando.php.ini
services:
  appserver:
    overrides:
      environment:
        SIMPLETEST_BASE_URL: "http://localhost/"
        SIMPLETEST_DB: "mysql://drupal9:drupal9@database/drupal9"
        BROWSERTEST_OUTPUT_DIRECTORY: "./sites/simpletest"
  pma:
    type: phpmyadmin
    hosts:
      - database
  Redis:
    type: redis
    portforward: 6379
  varnish:
    type: varnish
    backends:
      - appserver
    backend_port: 80
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
tooling:
  test:
    service: appserver
    cmd: "php ./vendor/bin/phpunit --verbose -c ./phpunit.xml"
proxy:
  phpmyadmin:
    - phpmyadmin.api_practice.lndo.site
  mailhog:
    - mail.lndo.site
