name: api_practice
recipe: drupal9
config:
  webroot: .
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  Redis:
    type: redis
    portforward: 6379
proxy:
  phpmyadmin:
    - phpmyadmin.api_practice.lndo.site