name: api_practice
recipe: drupal9
config:
  webroot: .
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  Redis:
    type: redis
    portforward: 6379
  varnish:
    type: varnish
    backends:
      - appserver
    backend_port: 80
proxy:
  phpmyadmin:
    - phpmyadmin.api_practice.lndo.site