<?php

use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */

function cartmodule_theme($existing, $type, $theme, $path)
{
  return [
    'cartblock' => [
      'variables' => ['content' => NULL],
    ],
    'checkout' => [
      'variables' => ['content' => NULL],
    ],
    'thanks' => [
      'variables' => ['content' => NULL],
    ]
  ];
}
function cartmodule_preprocess(&$variables, $hook)
{
  $module_handler = Drupal::service('module_handler');
  $path = $module_handler->getModule('cartmodule')->getPath();

  $query = \Drupal::database()->select('cartmodule', 't');
  $query->addExpression('SUM("quantity")');
  $count = $query->execute()->fetchField();
  $count = $count ? $count : 0;

  // if(isset($variables['region']) && $variables['region'] == 'content'){
  $variables['module_path'] = $path;
  $variables['product_count'] = $count;
  // }
}

function cartmodule_mail($key, &$message, $params)
{
  $options = array(
    'langcode' => $message['langcode'],
  );
  switch ($key) {
    case 'order':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      // $message['subject'] = $this->t('Your mail subject Here: @title', array('@title' => $params['title']), $options);
      $message['subject'] = $params['title'];
      $message['body'][] = Html::escape($params['message']);
      break;
  }
}
