_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    expanded: false
    weight: 0
  standard__front_page:
    weight: -50
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__testmenu__1':
    expanded: true
    parent: 'admin:'
    weight: 0
    menu_name: main
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__testmenu__2':
    expanded: true
    parent: 'admin:'
    weight: 1
    menu_name: main
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__testmenu__3':
    expanded: true
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.testmenu.1'
    weight: 0
    menu_name: main
    enabled: true
