_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 90a78f79-d3fe-4a2e-8935-4f9929e25b06
name: 'book shop'
mail: bookshop@mail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
